//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Korchevny.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoAboutPatient2
    {
        public string FullName { get; set; }
        public string Title { get; set; }
        public string FullNameEmp { get; set; }
        public string Name { get; set; }
    }
}
